#!/bin/sh
sudo apt install build-essential dkms -y
git clone https://github.com/gnab/rtl8812au.git
rm -rf rtl8812au/os_dep/linux/usb_intf.c
mv rtl8812au-installer/usb_intf.c rtl8812au/os_dep/linux/
sudo mv rtl8812au /usr/src/8812au-4.2.2
sudo dkms add -m 8812au -v 4.2.2
sudo dkms build -m 8812au -v 4.2.2
sudo dkms install -m 8812au -v 4.2.2
